name: KuCoin Market Scanner

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check files
        run: |
          echo "Current directory:"
          pwd

          echo "Files:"
          ls -la

          echo "Python:"
          python --version

          echo "KuCoin script:"
          ls -l kucoin_strategy.py

      - name: Run KuCoin scanner
        run: |
          echo "========================================"
          echo "Starting kucoin_strategy.py"
          echo "========================================"

          python -u kucoin_strategy.py

          echo "========================================"
          echo "Python script finished"
          echo "========================================"